version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
