name = "dracula-hugo-theme"
license = "MIT"
description = "My Dracula theme for Hugo static site generator"
homepage = "https://github.com/melvyndekort/dracula-hugo-theme"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Melvyn de Kort"
  homepage = "https://linktr.ee/melvyndekort"
